markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]   
highlighter: pygments
permalink: none
sitename: 代码段

chapters:
- introduction
- myself

introduction: 导论
myself: 临时（我自己）