markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]   
highlighter: pygments
permalink: none
sitename: 代码段

chapters:
- introduction
- oop
- dom 
- myself

introduction: 导论
oop: 面向对象编程
dom: DOM
myself: 临时（我自己）