markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]   
highlighter: pygments
permalink: none
sitename: 代码段

chapters:
- introduction
- code
- boss

introduction: 导论
code: 代码段搜集
boss: 谈天说地