markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]   
highlighter: pygments
permalink: none
sitename: 这里是网站的名称

chapters:
- hou1
- hou2
- hou3
- hou4
- hou5
- hou6

hou1: [hou1]
hou2: [hou2]
hou3: [hou3]
hou4: [hou4]
hou5: [hou5]
hou6: [hou6]

